# Generated by Django 2.2.5 on 2021-09-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_1',
        ),
    ]
