# Generated by Django 2.2.5 on 2021-09-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210908_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='img_logo',
            field=models.ImageField(blank=True, null=True, upload_to='../media_root'),
        ),
    ]
